name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Update setiap hari (opsional)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg
